
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author bayer
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    AdministrarUsuario adminuser = new AdministrarUsuario("./usuarios.txt");

    ArrayList<Usuario> usuarios = new ArrayList();

    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jD_elegirtipo = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jb_artista = new javax.swing.JButton();
        jb_oyente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jd_tipoartista = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jt_usernuevoartista = new javax.swing.JTextField();
        jt_nombreArtistico = new javax.swing.JTextField();
        js_edadnuevoartista = new javax.swing.JSpinner();
        jp_nuevaclaveartista = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jd_tipooyente = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jt_usernuevooyente = new javax.swing.JTextField();
        jp_nuevaclaveoyente = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        js_edadnuevooyente = new javax.swing.JSpinner();
        jf_artistinicio = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_lanzas = new javax.swing.JTree();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jf_clienteinicio = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt_username = new javax.swing.JTextField();
        jp_contra = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jb_registrarse = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jb_artista.setBackground(new java.awt.Color(0, 204, 0));
        jb_artista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_artista.setText("Artista");
        jb_artista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_artistaMouseClicked(evt);
            }
        });

        jb_oyente.setBackground(new java.awt.Color(0, 204, 0));
        jb_oyente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_oyente.setText("Oyente");
        jb_oyente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_oyenteMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Aprete su tipo de Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_oyente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel4)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jb_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jb_oyente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jD_elegirtipoLayout = new javax.swing.GroupLayout(jD_elegirtipo.getContentPane());
        jD_elegirtipo.getContentPane().setLayout(jD_elegirtipoLayout);
        jD_elegirtipoLayout.setHorizontalGroup(
            jD_elegirtipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jD_elegirtipoLayout.setVerticalGroup(
            jD_elegirtipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 204, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nuevo Artista");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 20, 213, 53));

        jLabel6.setBackground(new java.awt.Color(0, 204, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Username:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 91, 99, 36));

        jLabel7.setBackground(new java.awt.Color(0, 204, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Edad:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 145, 99, 36));

        jLabel8.setBackground(new java.awt.Color(0, 204, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Contraseña:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 199, 99, 36));

        jLabel9.setBackground(new java.awt.Color(0, 204, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Nombre Artistico:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 253, -1, 36));

        jt_usernuevoartista.setBackground(new java.awt.Color(0, 204, 0));
        jPanel3.add(jt_usernuevoartista, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 91, 202, 36));

        jt_nombreArtistico.setBackground(new java.awt.Color(0, 204, 0));
        jPanel3.add(jt_nombreArtistico, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 254, 202, 36));

        js_edadnuevoartista.setValue(18);
        jPanel3.add(js_edadnuevoartista, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 145, 89, 36));

        jp_nuevaclaveartista.setBackground(new java.awt.Color(0, 204, 0));
        jPanel3.add(jp_nuevaclaveartista, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 199, 202, 36));

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setText("Crear Cuenta");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 308, 202, 51));

        javax.swing.GroupLayout jd_tipoartistaLayout = new javax.swing.GroupLayout(jd_tipoartista.getContentPane());
        jd_tipoartista.getContentPane().setLayout(jd_tipoartistaLayout);
        jd_tipoartistaLayout.setHorizontalGroup(
            jd_tipoartistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        jd_tipoartistaLayout.setVerticalGroup(
            jd_tipoartistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        jd_tipooyente.setPreferredSize(new java.awt.Dimension(602, 467));
        jd_tipooyente.setSize(new java.awt.Dimension(602, 467));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(602, 467));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 204, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("Crear Cuenta");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 202, 51));

        jLabel10.setBackground(new java.awt.Color(0, 204, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nuevo Oyente");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 20, 213, 53));

        jt_usernuevooyente.setBackground(new java.awt.Color(0, 204, 0));
        jPanel4.add(jt_usernuevooyente, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 91, 202, 36));

        jp_nuevaclaveoyente.setBackground(new java.awt.Color(0, 204, 0));
        jPanel4.add(jp_nuevaclaveoyente, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 199, 202, 36));

        jLabel11.setBackground(new java.awt.Color(0, 204, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Contraseña:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 199, 99, 36));

        jLabel12.setBackground(new java.awt.Color(0, 204, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Edad:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 145, 99, 36));

        jLabel13.setBackground(new java.awt.Color(0, 204, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Username:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 91, 99, 36));

        js_edadnuevooyente.setValue(12);
        jPanel4.add(js_edadnuevooyente, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 145, 89, 36));

        javax.swing.GroupLayout jd_tipooyenteLayout = new javax.swing.GroupLayout(jd_tipooyente.getContentPane());
        jd_tipooyente.getContentPane().setLayout(jd_tipooyenteLayout);
        jd_tipooyenteLayout.setHorizontalGroup(
            jd_tipooyenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tipooyenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jd_tipooyenteLayout.setVerticalGroup(
            jd_tipooyenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tipooyenteLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jf_artistinicio.setSize(new java.awt.Dimension(566, 425));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(51, 255, 0));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jt_lanzas.setBackground(new java.awt.Color(0, 255, 0));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Lanzamientos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Albums");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Singles");
        treeNode1.add(treeNode2);
        jt_lanzas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_lanzas);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inicio", jPanel6);

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mis PlayLists", jPanel7);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("PlayLists Publicas", jPanel8);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout jf_artistinicioLayout = new javax.swing.GroupLayout(jf_artistinicio.getContentPane());
        jf_artistinicio.getContentPane().setLayout(jf_artistinicioLayout);
        jf_artistinicioLayout.setHorizontalGroup(
            jf_artistinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_artistinicioLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jf_artistinicioLayout.setVerticalGroup(
            jf_artistinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_artistinicioLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane2.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setForeground(new java.awt.Color(51, 255, 0));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Inicio", jPanel10);

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Mis Playlists", jPanel11);

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Playlists publicas", jPanel12);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout jf_clienteinicioLayout = new javax.swing.GroupLayout(jf_clienteinicio.getContentPane());
        jf_clienteinicio.getContentPane().setLayout(jf_clienteinicioLayout);
        jf_clienteinicioLayout.setHorizontalGroup(
            jf_clienteinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_clienteinicioLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 300, Short.MAX_VALUE))
        );
        jf_clienteinicioLayout.setVerticalGroup(
            jf_clienteinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_clienteinicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(602, 467));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(602, 467));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido a Spotify Mejorado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 270, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 140, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre de Usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 140, 30));

        jt_username.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.add(jt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 250, 30));

        jp_contra.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.add(jp_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 250, 30));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Iniciar Sesion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 150, 40));

        jb_registrarse.setBackground(new java.awt.Color(0, 204, 0));
        jb_registrarse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jb_registrarse.setText("Registrarse");
        jb_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registrarseMouseClicked(evt);
            }
        });
        jPanel1.add(jb_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_artistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_artistaMouseClicked
        jd_tipoartista.pack();
        jd_tipoartista.setModal(true);
        jd_tipoartista.setLocationRelativeTo(jD_elegirtipo);
        jd_tipoartista.setVisible(true);
    }//GEN-LAST:event_jb_artistaMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (jt_usernuevoartista.getText().isBlank() || jp_nuevaclaveartista.getText().isBlank() || (Integer) js_edadnuevoartista.getValue() < 18 || jt_nombreArtistico.getText().isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Hay minimo algo en blanco o la edad es menor de 18", "ERROR FAMI", 2);
        } else {
            boolean puede2 = true;
            for (int i = 0; i < usuarios.size(); i++) {
                if (jt_usernuevoartista.getText().equals(usuarios.get(i).getUsername())) {
                    puede2 = false;
                    i = usuarios.size() + 454;
                } else {
                    puede2 = true;
                }
            }
            if (puede2) {
                usuarios.add(new Artista(jt_nombreArtistico.getText(), jt_usernuevoartista.getText(), jp_nuevaclaveartista.getText(), (Integer) js_edadnuevoartista.getValue()));
                jt_usernuevoartista.setText("");
                jp_nuevaclaveartista.setText("");
                js_edadnuevoartista.setValue(18);
                jt_nombreArtistico.setText("");
                jd_tipoartista.setVisible(false);
                jD_elegirtipo.setVisible(false);
                JOptionPane.showMessageDialog(jd_tipoartista, "Se ha creado el artista exitosamente");
            } else {
                JOptionPane.showMessageDialog(jd_tipoartista, "Ya alguien tiene ese usuario", "ERROR FAMI", 2);
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (jt_usernuevooyente.getText().isBlank() || jp_nuevaclaveoyente.getText().isBlank() || (Integer) js_edadnuevooyente.getValue() < 12) {
            JOptionPane.showMessageDialog(rootPane, "Hay minimo algo en blanco o la edad es menor de 12", "ERROR FAMI", 2);
        } else {
            boolean puede = true;
            for (int i = 0; i < usuarios.size(); i++) {
                if (jt_usernuevooyente.getText().equals(usuarios.get(i).getUsername())) {
                    puede = false;
                    i = usuarios.size() + 50000;
                } else {
                    puede = true;
                }
            }
            if (puede) {
                usuarios.add(new Oyente(jt_usernuevooyente.getText(), jp_nuevaclaveoyente.getText(), (Integer) js_edadnuevooyente.getValue()));
                jt_usernuevooyente.setText("");
                jp_nuevaclaveoyente.setText("");
                js_edadnuevooyente.setValue(12);
                jd_tipooyente.setVisible(false);
                jD_elegirtipo.setVisible(false);
                JOptionPane.showMessageDialog(jd_tipooyente, "Se ha creado exitosamente el oyente");
            } else {
                JOptionPane.showMessageDialog(jd_tipooyente, "Ya alguien tiene ese usuario", "ERROR FAMI", 2);
            }
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jb_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registrarseMouseClicked
        jD_elegirtipo.pack();
        jD_elegirtipo.setModal(true);
        jD_elegirtipo.setLocationRelativeTo(this);
        jD_elegirtipo.setVisible(true);
    }//GEN-LAST:event_jb_registrarseMouseClicked

    private void jb_oyenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_oyenteMouseClicked
        jd_tipooyente.pack();
        jd_tipooyente.setModal(true);
        jd_tipooyente.setLocationRelativeTo(jD_elegirtipo);
        jd_tipooyente.setVisible(true);
    }//GEN-LAST:event_jb_oyenteMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        boolean entra = false;
        int copiai=0;
        if (usuarios.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay ni un usuario", "ERROR FAMI", 2);
        }else{
            for (int i = 0; i < usuarios.size(); i++) {
                if (jt_username.getText().equals(usuarios.get(i).getUsername())) {
                      if (jp_contra.getText().equals(usuarios.get(i).getContra())){
                        entra = true;
                        copiai = i;
                        i = usuarios.size()+60;
                    }else{
                        JOptionPane.showMessageDialog(this, "Contraseña invalida", "ERROR FAMI", 2);
                        entra = false;
                      }
                }else{
                    JOptionPane.showMessageDialog(this, "Usuario Invalido", "ERROR FAMI", 2);
                }
            }
            if (entra) {
                jt_username.setText("");
                jp_contra.setText("");
                this.setVisible(false);
                if (usuarios.get(copiai) instanceof Artista) {
                    DefaultTreeModel modelo = (DefaultTreeModel)jt_lanzas.getModel();
                    DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
                    for (Album a : ((Artista)(usuarios.get(copiai))).getAlbumespubblicados()) {
                        DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(a);
                        for (Cancion c : a.getCanciones()) {
                            DefaultMutableTreeNode cc = new DefaultMutableTreeNode(c);
                            nodo.add(cc);
                        }
                        raiz.add(nodo);
                    }
                    jf_artistinicio.setVisible(true);
                    jf_artistinicio.setLocationRelativeTo(this);
                    
                }else{
                    jf_clienteinicio.setVisible(true);
                    jf_clienteinicio.setLocationRelativeTo(this);
                }
            }
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jD_elegirtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jb_artista;
    private javax.swing.JButton jb_oyente;
    private javax.swing.JButton jb_registrarse;
    private javax.swing.JDialog jd_tipoartista;
    private javax.swing.JDialog jd_tipooyente;
    private javax.swing.JFrame jf_artistinicio;
    private javax.swing.JFrame jf_clienteinicio;
    private javax.swing.JPasswordField jp_contra;
    private javax.swing.JPasswordField jp_nuevaclaveartista;
    private javax.swing.JPasswordField jp_nuevaclaveoyente;
    private javax.swing.JSpinner js_edadnuevoartista;
    private javax.swing.JSpinner js_edadnuevooyente;
    private javax.swing.JTree jt_lanzas;
    private javax.swing.JTextField jt_nombreArtistico;
    private javax.swing.JTextField jt_username;
    private javax.swing.JTextField jt_usernuevoartista;
    private javax.swing.JTextField jt_usernuevooyente;
    // End of variables declaration//GEN-END:variables
}
